### ISSUE TITLE
Adding with index

### ISSUE THREAD

**Issue by vitidev** [theblitz/ObservableCollections#4]
`removeAt(index: Int)` sends element index

     signalChanged(ObservableCollectionsAction.RemoveAt, actionInt = index, resultElement = resultElement)

but `add(index: Int, element: X)` with an index for unknown reason not

    signalChanged(ObservableCollectionsAction.Add, actionElement = element)

Why? Let him send it too.

**Comment by theblitz** [comment]
Thank you.

Looking into it now.

**Comment by theblitz** [comment]
This will be implemented in Version 1.4 which is due for release in the next few days.

**Comment by theblitz** [comment]
Version 1.4 is now available with this fix
