### ISSUE TITLE
Unexpected execution order with 1.4.0

### ISSUE THREAD

**Issue by vitidev** [theblitz/ObservableCollections#5]
I have the ManActivity as navigation host and start LoginFragment (startDestination), where do i get navigation drawer and lock it. 
When I updated the package to 1.4.0, I started getting NRE when I tried to get navdrawer.

The order of execution has changed.

v1.3.1
1 MainActivity.onCreate start
2 MainActivity.onCreate call   setContentView(R.layout.activity_main)
3 MainActivity.onCreate executes the rest of the code
4 MainActivity.onCreate finish
...
5 **LoginFragment.onCreateView** execute

v1.4.0
1 MainActivity.onCreate start
2 MainActivity.onCreate call   setContentView(R.layout.activity_main)
3 **LoginFragment.onCreateView** execute (NRE  becouse nav is not initialized yet)
4 MainActivity.onCreate executes the rest of the code
5 MainActivity.onCreate finish

I am begginer in android development. And so the question. Is this a bug of   ObservableCollections or am I misunderstanding the order of execution and did the wrong authorization?

**Comment by vitidev** [comment]
I have no idea how this is possible, but the problem is easily reproducible

1 create empty "Navigation Drawer" project (kotlin, any api level. I tried 23 and 27)
2 setup log markers

MainActivity

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.i("TRACEMARKER", "activity 1")
        setContentView(R.layout.activity_main)
        Log.i("TRACEMARKER", "activity 2")

HomeFragment

    override fun onCreateView(
            inflater: LayoutInflater,
            container: ViewGroup?,
            savedInstanceState: Bundle?
    ): View? {
        Log.i("TRACEMARKER", "fragment")
        homeViewModel =
                ViewModelProviders.of(this).get(HomeViewModel::class.java)

3 add to gradle

    implementation 'il.co.theblitz:observablecollections:1.3.1'

result:

    I/TRACEMARKER: activity 1
    I/TRACEMARKER: activity 2
    I/TRACEMARKER: fragment

4 modify gradle
   
    implementation 'il.co.theblitz:observablecollections:1.4.0'

result:

    I/TRACEMARKER: activity 1   
    I/TRACEMARKER: fragment
    I/TRACEMARKER: activity 2

**Comment by theblitz** [comment]
@vitidev 
I am trying to figure out exactly what you mean.
I don't any referenced to ObserveableCollections in your code except in gradle.

Is there some other code missing or have I misunderstood something?

**Comment by vitidev** [comment]
@theblitz 
Exactly. I got NRE in work project and tried to isolate the problem.
To reproduce the problem, you just need to have it in gradle. Use in code is optional

**Comment by theblitz** [comment]
The only thing I can think of is that I updated all the referenced SDKs to the latest versions.
Maybe this is causing some sort of a clash.

**Comment by vitidev** [comment]
I checked. The reason is bug (maybe not bug. I do not know, I am begginer and I don’t know such details) in appcompat

     implementation 'androidx.appcompat:appcompat:1.3.0-alpha02'

Perhaps you shouldn't make dependencies on non-stable versions

**Comment by theblitz** [comment]
Is it noted as a bug somewhere?
Reason I switched was that Android Studio kinda insisted.
I'll see what I can do to change it back.

**Comment by theblitz** [comment]
I just did another test without ObservableCollections and just switching between androidx.appcompat:appcompat:1.1.0 and androidx.appcompat:appcompat:1.2.0
It is that that is causing the problem.
Seems that something changed in appcompat between 1.1.0 and 1.2.0

**Comment by vitidev** [comment]
>Is it noted as a bug somewhere?

I did not find. But I don’t know what to look for

>Seems that something changed in appcompat between 1.1.0 and 1.2.0

I cannot confirm. for me 1.2.0 works correctly

**Comment by theblitz** [comment]
So, after even more looking :) it is definitely a problem with appcompat:1.3.0 as you said
I will make the changes in the next few days and release an updated version (probably with be 1.4.1).

In the meantime, you can force gradle to ignore the "inherited" version in this way:
    implementation ('il.co.theblitz:observablecollections:1.4.0') {
        exclude group: 'androidx.appcompat', module: 'appcompat'
    }

Notice the "(" and ")" before and after the name.

**Comment by theblitz** [comment]
Fixed in Version 1.4.1

As a side note: You should open a bug fro Android appcompat on Google's site
