### ISSUE TITLE
range mutations support

### ISSUE THREAD

**Issue by vitidev** [theblitz/ObservableCollections#6]
RecyclerView support range notification (notifyItemRangeRemoved, notifyItemRangeChanged, notifyItemRangeInserted)

Is there a reason why the ObservableCollectionsdoesn't support such mutations?

I have to delete one element at a time

**Comment by theblitz** [comment]
ObservableCollections supports the same notifications that are connected to contents the actual list itself.
Those ones you have given are connected to the display of the list.

If the list permits multiple removal, like RemoveIf, then it does return the list of items removed.
